export {CV} from './ui/CV'
export {AddEducation} from './ui/AddEducation'
export {AddHardskills} from './ui/AddHardskills'
export {AddInfo} from './ui/AddInfo'
export {AddLanguages} from './ui/AddLanguages'
export {AddProfile} from './ui/AddProfile'
export {AddSoftskills} from './ui/AddSoftskills'
export {AddWork} from './ui/AddWork'