export {default} from 'src/pages/cv/Preview'
export {InfoPage} from './ui/InfoPage'
export { ProfilePage } from './ui/ProfilePage'
export { EducationPage } from './ui/EducationPage'
export { WorkPage } from './ui/WorkPage'
export { LanguagesPage } from './ui/LanguagesPage'
export { HardskillsPage } from './ui/HardskillsPage'
export { SoftskillsPage } from './ui/SoftskillsPage'